#!/bin/bash

set -e
cd `dirname $0`
cd .. # .codapt
cd .. # project root

docker/compose build

# run typecheck & lint in app container
docker/compose run --no-deps --rm app bash -c "npm install --production=false --ignore-scripts && npx prisma generate && npm run typecheck && npm run lint"
