#!/bin/bash

set -e
cd `dirname $0`
cd .. # .codapt
cd .. # project root

docker/compose build

# run typecheck & lint in app container
docker/compose run --no-deps --rm app bash -c "pnpm install --production=false --ignore-scripts && pnpm exec prisma generate && pnpm run typecheck && pnpm run lint"
