#!/bin/bash

set -e
cd `dirname $0`
cd .. # .codapt
cd .. # project root

# stop all containers
docker/compose down

# install dependencies, generate prisma client, push schema
docker/compose run --rm app bash -c "pnpm install --production=false --ignore-scripts && pnpm exec prisma generate && pnpm exec prisma db push --accept-data-loss"
