#!/bin/bash

set -e
cd `dirname $0`
cd .. # .codapt
cd .. # project root

# stop all containers
docker/compose down

# install dependencies, generate prisma client, push schema
docker/compose run --rm app bash -c "npm install --production=false --ignore-scripts && npx prisma generate && npx prisma db push --accept-data-loss"
